name: Deploy React App
on:
  push:
    branches:
      - master  
  workflow_dispatch:

env:
  NODE_VERSION: '21.2.0' 

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          
      - name: Build website
        run: |
          npm run build
        env:
          CI: false 
          
      - name: Test website
        run: |
          npm test
        env:
          CI: true
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages 
          folder: build     
          clean: true     
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/
